### ISSUE TITLE
Add transactions in batch through text file

### ISSUE THREAD

**Issue by vitokhangnguyen** [utkuufuk/google-budget#12]
Right now, all transactions are added individually. I think it is a good idea for the user to be able to add many of them at the same time through a text file.

A scenario this can be useful is that the user does not have a network connection at the moment. Writing all transactions down on a file and process them at the same time would help.

The new command syntax can be:
```
budget add --file-path ~/path/to/text/file.txt
```

File format can be:
```
# Text file can have comments and should be ignored
expense: 900, Rent, House
expense: Aug 8, 60, Gas, Other
income: Oct 11, 2000, Paycheck, Paycheck
income: 150, Paycheck, Bonus
```

How do you think?

**Comment by utkuufuk** [comment]
@vitokhangnguyen TBH I don't expect this to be used as much as `edit` or `delete`, but might prove useful once in a while in some cases as you mentioned.

I'd prefer a command like this though:
```
budget insert /path/to/file
```

And a format consistent with `expense` & `income` commands, so the user won't have to remember 2 formats:
```
expense "900, Rent, House"
expense "Aug 8, 60, Gas, Other"
income "Oct 11, 2000, Paycheck, Paycheck"
income "150, Paycheck, Bonus"
```

Feel free to work on this if you like 👍

**Comment by vitokhangnguyen** [comment]
My colleague [Grommers00](https://github.com/Grommers00) and I will work on this. We will try to get it done as soon as possible given the time we have.

**Comment by Grommers00** [comment]
Yes, we will work on it together.
