### ISSUE TITLE
Add capability to edit existing transaction entry

### ISSUE THREAD

**Issue by utkuufuk** [utkuufuk/google-budget#9]

**Comment by vitokhangnguyen** [comment]
Hi,
I would very much like to work on this issue!

**Comment by utkuufuk** [comment]
@vitokhangnguyen That'd be great!

Firstly we would need to display row numbers next to each row within the output of `budget log` command.

Then we can define a new command to edit the selected row like so:
``` sh
# let's say we want to edit line 12
budget edit 12 "<new_date>, <new_amount>, <new_description>, <new_category>"
```

Of course I'm open to suggestions if you have something else in mind in terms of how to use the new command.

**Comment by vitokhangnguyen** [comment]
Hi,
Sorry for not reaching to you for a while. I am setting up the program and encounter this error when I ran `./install.sh`:
```shell
  File "createtoken.py", line 1, in <module>
    from oauth2client import file, client, tools
ModuleNotFoundError: No module named 'oauth2client'
```
Although apparently installed, the `createtoken.py` module still cannot recognize the module.
I am doing this in a virtual environment.

**Comment by utkuufuk** [comment]
Maybe you could try running

``` sh
pip3 install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib oauth2client
```

separately and see if you get any errors. 

If you don't, running 
``` sh
python3 createtoken.py
```

should work as long as you have python3 and pip3 installed.

**Comment by vitokhangnguyen** [comment]
I tried that and the output is many "Requirement already up-to-date/satisfied" including this line:
```
Requirement already up-to-date: oauth2client in d:\my workspace\budget-cli\venv\lib\site-packages (4.1.3)
```
However, when I run `python3 createtoken.py`, it still raises error:
```
Traceback (most recent call last):
  File "createtoken.py", line 1, in <module>
    from oauth2client import file, client, tools
ModuleNotFoundError: No module named 'oauth2client'
```

**Comment by vitokhangnguyen** [comment]
Actually, I fixed the issue by changing all the commands from "python3" to "python" and "pip3" to "pip". I do not know why since I do not have Python 2 on my computer and the only version is Python 3.7.4.

**Comment by utkuufuk** [comment]
It's very strange, I'm glad you found a solution though :+1:

**Comment by vitokhangnguyen** [comment]
Hi @utkuufuk,

I have done the basics of the feature. Just polishing and adding a few details now. The way I construct the new command is:
```shell
budget edit [income | expense] [line_index] [new_transsaction]
```
The line number will display in the `budget log` command and is separated between the expense and income (that's why the 3rd argument indicating which one to edit is needed). Here's an example:
```
Oct Expense Log
===============================================================================      
   1   08/09/2000    $1,500.00    Rent                                Home
   2   13/10/2019       $35.00    Groceries                           Home
   3   13/10/2019        $5.00    Pizza                               Food
   4   13/10/2019        $5.00    Pizza                               Food

Oct Income Log
===============================================================================      
   1   08/09/2000    $2,000.00    Paycheck                            Paycheck       
   2   13/10/2019       $75.00    Tax Return                          Other
   3   13/10/2019      $100.00    Scholarship                         Bonus
   4   13/10/2019      $100.00    Scholarship                         Bonus
   5   13/10/2019       $75.00    Tax Return                          Other
```
Is this what you want? Tell me if you want me to improve something.
